/*
 * File: app/view/CustomerDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CustomerDetail', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.customerdetail',

    padding: 10,
    layout: {
        align: 'stretch',
        padding: 10,
        type: 'vbox'
    },
    title: '{name}',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 173,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    title: ''
                },
                {
                    xtype: 'container',
                    margins: '10 0',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-add',
                            text: 'New Order'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});