/*
 * File: app/view/CustomerDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CustomerDetail', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.customerdetail',

    requires: [
        'MyApp.view.ContactInfo'
    ],

    padding: 10,
    layout: {
        align: 'stretch',
        padding: 10,
        type: 'vbox'
    },
    title: '{name}',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 173,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'contactinfo',
                            flex: 1,
                            border: 1,
                            margin: '0 20 0 0',
                            padding: 10
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margins: '10 0',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-add',
                            text: 'New Order'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    itemId: 'ordersGrid',
                    title: '',
                    disableSelection: true,
                    store: 'Orders',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'id',
                            text: 'Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'orderNo',
                            text: 'Orders',
                            flex: 1
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'orderDate',
                            text: 'OrderDate'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'shippedDate',
                            text: 'ShippedDate'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'total',
                            text: 'Total'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'balance',
                            text: 'Balance'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    setCustomer: function(customer) {
        this.setTitle(customer.get('name'));
        this.down('contactinfo').update(customer.getData());
        this.customer = customer;
    }

});