/*
 * File: app/model/Customer.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Customer', {
    extend: 'Ext.data.Model',

    idProperty: 'customerId',

    fields: [
        {
            name: 'customerId'
        },
        {
            name: 'name'
        },
        {
            name: 'address'
        },
        {
            name: 'city'
        },
        {
            name: 'state'
        },
        {
            name: 'zip'
        },
        {
            name: 'phone'
        },
        {
            name: 'fax'
        },
        {
            name: 'category'
        },
        {
            name: 'balance',
            type: 'float'
        }
    ]
});