/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'customers',
            selector: 'main > #cards'
        },
        {
            ref: 'customerDetail',
            selector: 'customerdetail'
        },
        {
            ref: 'main',
            selector: 'main'
        },
        {
            ref: 'cardCt',
            selector: '#cardCt'
        }
    ],

    onBreadcrumbsBreadcrumbactivate: function(breadcrumbs, index, eventOptions) {
        this.getCardCt().getLayout().setActiveItem(index);
    },

    onCustomerSelect: function(customer, eventOptions) {
        var detailCard = this.getCustomerDetail();
        detailCard.setCustomer(customer);
        detailCard.ownerCt.getLayout().setActiveItem(detailCard);
        
        var args = {
            params: {
                customerId: customer.getId()
            }
        };
        this.getOrdersStore().load(args);
        
    },

    onCardSwitch: function(component, eOpts) {
        this.getMain().updateBreadcrumbs();
    },

    init: function(application) {
        this.control({
            "breadcrumbs": {
                breadcrumbactivate: this.onBreadcrumbsBreadcrumbactivate
            },
            "customers": {
                customerselect: this.onCustomerSelect
            },
            "main > #cardCt > component": {
                activate: this.onCardSwitch
            }
        });
    }

});
